/**
 * Interface representing a service that can interact with an AI API.
 */
export interface IAIService {
    /**
     * Ask the AI a question and receive a response.
     * @param question The question to ask
     * @param context Optional context to provide AI with
     * @throws If there is an issue with the request to the API
     * @returns The response generated by the AI
     */
    ask(question: string, context?: string): Promise<string>

    /**
     * Have the AI generate notes from a given file.
     * @param file The file to generate notes from
     * @returns The response from the AI in an HTML-safe format
     */
    generateNotes(file: Blob): Promise<string>
}